<a href="https://colab.research.google.com/github/PuruBhatnagar1197/Machine-Learning-Revision/blob/main/AUC_ROC_curve_revision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/npradaschnor/Pima-Indians-Diabetes-Dataset/master/diabetes.csv')

In [5]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [36]:
x_train, x_test,y_train,y_test=train_test_split(df.iloc[:,0:-1],df['Outcome'],test_size=0.2, random_state=1)

In [37]:
model=LogisticRegression()
model.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning:

lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression



LogisticRegression()

In [38]:
model.predict(x_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0])

In [39]:
model.predict_proba(x_test)### how both class ke prob aaye hai

array([[0.5474997 , 0.4525003 ],
       [0.68726519, 0.31273481],
       [0.84936837, 0.15063163],
       [0.96018064, 0.03981936],
       [0.79995133, 0.20004867],
       [0.75003074, 0.24996926],
       [0.63617514, 0.36382486],
       [0.89929467, 0.10070533],
       [0.86615453, 0.13384547],
       [0.83206645, 0.16793355],
       [0.54729885, 0.45270115],
       [0.92492254, 0.07507746],
       [0.00888179, 0.99111821],
       [0.24786929, 0.75213071],
       [0.94728923, 0.05271077],
       [0.25482599, 0.74517401],
       [0.77578256, 0.22421744],
       [0.68843629, 0.31156371],
       [0.88185323, 0.11814677],
       [0.8329691 , 0.1670309 ],
       [0.5530041 , 0.4469959 ],
       [0.82231253, 0.17768747],
       [0.03131151, 0.96868849],
       [0.73549233, 0.26450767],
       [0.93214869, 0.06785131],
       [0.62529887, 0.37470113],
       [0.82652747, 0.17347253],
       [0.19131838, 0.80868162],
       [0.91557079, 0.08442921],
       [0.42030164, 0.57969836],
       [0.

In [40]:
y_scores=model.predict_proba(x_test)[:,1] ### give probbaility of all class 1.

In [41]:
y_scores

array([0.4525003 , 0.31273481, 0.15063163, 0.03981936, 0.20004867,
       0.24996926, 0.36382486, 0.10070533, 0.13384547, 0.16793355,
       0.45270115, 0.07507746, 0.99111821, 0.75213071, 0.05271077,
       0.74517401, 0.22421744, 0.31156371, 0.11814677, 0.1670309 ,
       0.4469959 , 0.17768747, 0.96868849, 0.26450767, 0.06785131,
       0.37470113, 0.17347253, 0.80868162, 0.08442921, 0.57969836,
       0.43040921, 0.33382114, 0.06066446, 0.66183458, 0.13929037,
       0.6002382 , 0.09989091, 0.19115845, 0.0975119 , 0.58761361,
       0.19896847, 0.08279902, 0.03937734, 0.3562357 , 0.07725975,
       0.02226581, 0.71431646, 0.83024163, 0.08102894, 0.12656903,
       0.00863146, 0.20808326, 0.87650428, 0.04740486, 0.78236861,
       0.10617052, 0.62410012, 0.34216431, 0.54135505, 0.13534588,
       0.62319284, 0.01491135, 0.72449429, 0.18729719, 0.33070358,
       0.10124352, 0.01033961, 0.29183934, 0.72412478, 0.65272494,
       0.88289795, 0.71666726, 0.62730019, 0.0157817 , 0.71076

In [42]:
from sklearn.metrics import roc_curve

In [43]:
fpr, tpr, thresholds=roc_curve(y_test,y_scores) #### it gives output as three arrays one is fpr, tpr, and thresholds

In [44]:
import plotly.graph_objects as go
import numpy as np


# Generate a trace for ROC curve
trace0 = go.Scatter(
    x=fpr,
    y=tpr,
    mode='lines',
    name='ROC curve'
)

# Only label every nth point to avoid cluttering
n = 10
indices = np.arange(len(thresholds)) % n == 0  # Choose indices where index mod n is 0

trace1 = go.Scatter(
    x=fpr[indices],
    y=tpr[indices],
    mode='markers+text',
    name='Threshold points',
    text=[f"Thr={thr:.2f}" for thr in thresholds[indices]],
    textposition='top center'
)


# Diagonal line
trace2 = go.Scatter(
    x=[0, 1],
    y=[0, 1],
    mode='lines',
    name='Random (Area = 0.5)',
    line=dict(dash='dash')
)

data = [trace0, trace1, trace2]

# Define layout with square aspect ratio
layout = go.Layout(
    title='Receiver Operating Characteristic',
    xaxis=dict(title='False Positive Rate'),
    yaxis=dict(title='True Positive Rate'),
    autosize=False,
    width=800,
    height=800,
    showlegend=False
)

# Define figure and add data
fig = go.Figure(data=data, layout=layout)

# Show figure
fig.show()


In [45]:
### for calculating optimal threshold points
opt_index=np.argmax(tpr-fpr)
opti_threshold =thresholds[opt_index]
opti_threshold

0.34699157524193214

In [48]:
import plotly.graph_objects as go
from sklearn.svm import SVC
from sklearn.metrics import roc_auc_score, roc_curve
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

### lr model
lr=LogisticRegression()
model_lr=lr.fit(x_train_scaled,y_train)
model_lr_scores=model_lr.predict_proba(x_test_scaled)[:,1]
lr_fpr, lr_tpr, lr_thresholds=roc_curve(y_test,model_lr_scores)
lr_auc=roc_auc_score(y_test,model_lr_scores)
### svm model
svm=SVC(probability=True)
model_svm=svm.fit(x_train_scaled,y_train)
model_svm_scores=model_svm.predict_proba(x_test_scaled)[:,1]
svm_fpr, svm_tpr, svm_thresholds=roc_curve(y_test,model_svm_scores)
svm_auc=roc_auc_score(y_test,model_svm_scores)


In [49]:
trace0 = go.Scatter(
    x=lr_fpr,
    y=lr_tpr,
    mode='lines',
    name=f'Logistic Regression (Area = {lr_auc:.2f})'
)

# Generate a trace for the SVM ROC curve
trace1 = go.Scatter(
    x=svm_fpr,
    y=svm_tpr,
    mode='lines',
    name=f'SVM (Area = {svm_auc:.2f})'
)

# Diagonal line
trace2 = go.Scatter(
    x=[0, 1],
    y=[0, 1],
    mode='lines',
    name='Random (Area = 0.5)',
    line=dict(dash='dash')
)

data = [trace0, trace1, trace2]

# Define layout with square aspect ratio
layout = go.Layout(
    title='Receiver Operating Characteristic',
    xaxis=dict(title='False Positive Rate'),
    yaxis=dict(title='True Positive Rate'),
    autosize=False,
    width=800,
    height=800,
    showlegend=True
)

# Define figure and add data
fig = go.Figure(data=data, layout=layout)

# Show figure
fig.show()
